//! Generate embedded 8-bit lookup tables for hash inversion.
//!
//! This example computes the preimages for all 256 hash values for each
//! 8-bit hash function and outputs them as Rust const arrays.
//!
//! Run with: `cargo run --example generate_tables`

use hash_inversion::{md5_8bit, mini_md5, mini_sha256, sha256_8bit};
use std::collections::HashMap;

/// Generate preimage lookup table for a hash function.
/// Returns a mapping from hash value to the smallest preimage (as bytes).
fn generate_lookup_table<F>(hash_fn: F) -> HashMap<u8, Vec<u8>>
where
    F: Fn(&[u8]) -> u8,
{
    let mut table: HashMap<u8, Vec<u8>> = HashMap::new();

    // First pass: single-byte inputs (0-255)
    for i in 0u8..=255 {
        let data = [i];
        let hash = hash_fn(&data);
        table.entry(hash).or_insert_with(|| data.to_vec());
    }

    // Second pass: two-byte inputs if needed
    if table.len() < 256 {
        for i in 0u16..=65535 {
            if table.len() >= 256 {
                break;
            }
            let data = i.to_le_bytes();
            let hash = hash_fn(&data);
            table.entry(hash).or_insert_with(|| data.to_vec());
        }
    }

    table
}

/// Format a lookup table as a Rust const array of preimages.
/// Each entry is the smallest preimage (1 or 2 bytes) for that hash value.
fn format_preimage_table(name: &str, table: &HashMap<u8, Vec<u8>>) -> String {
    let mut lines = Vec::new();

    lines.push(format!(
        "/// Precomputed preimage lookup table for {name} (8-bit)."
    ));
    lines.push(
        "/// Each entry maps hash value (index) to a preimage that produces that hash.".to_string(),
    );
    lines.push("/// Format: (length, byte0, byte1) where length is 1 or 2.".to_string());
    let const_name = name.to_uppercase().replace('-', "_");
    lines.push(format!(
        "pub const {const_name}_8BIT_PREIMAGES: [(u8, u8, u8); 256] = ["
    ));

    for hash_value in 0u8..=255 {
        let preimage = table.get(&hash_value).expect("Missing preimage");
        let (len, b0, b1) = if preimage.len() == 1 {
            (1u8, preimage[0], 0u8)
        } else {
            (2u8, preimage[0], preimage[1])
        };
        let comment = if preimage.len() == 1 {
            format!("hash {hash_value} -> [{b0}]")
        } else {
            format!("hash {hash_value} -> [{b0}, {b1}]")
        };
        lines.push(format!("    ({len}, {b0}, {b1}), // {comment}"));
    }

    lines.push("];".to_string());
    lines.join("\n")
}

fn main() {
    println!("// Auto-generated 8-bit lookup tables for hash inversion");
    println!("// Generated by: cargo run --example generate_tables");
    println!();

    // Generate MD5 8-bit table
    println!("// === Truncated MD5 (8-bit) ===");
    let md5_table = generate_lookup_table(md5_8bit);
    assert_eq!(md5_table.len(), 256, "MD5 table should have 256 entries");
    println!("{}", format_preimage_table("MD5", &md5_table));
    println!();

    // Generate SHA-256 8-bit table
    println!("// === Truncated SHA-256 (8-bit) ===");
    let sha256_table = generate_lookup_table(sha256_8bit);
    assert_eq!(
        sha256_table.len(),
        256,
        "SHA-256 table should have 256 entries"
    );
    println!("{}", format_preimage_table("SHA256", &sha256_table));
    println!();

    // Generate MiniMD5 table
    println!("// === MiniMD5 (custom 8-bit) ===");
    let mini_md5_table = generate_lookup_table(mini_md5);
    assert_eq!(
        mini_md5_table.len(),
        256,
        "MiniMD5 table should have 256 entries"
    );
    println!("{}", format_preimage_table("MINI_MD5", &mini_md5_table));
    println!();

    // Generate MiniSHA256 table
    println!("// === MiniSHA256 (custom 8-bit) ===");
    let mini_sha256_table = generate_lookup_table(mini_sha256);
    assert_eq!(
        mini_sha256_table.len(),
        256,
        "MiniSHA256 table should have 256 entries"
    );
    println!(
        "{}",
        format_preimage_table("MINI_SHA256", &mini_sha256_table)
    );
}
